#  production overrides
services:
  frontend:
    ports: ["80:80"]
    restart: always
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx # nginx потребує кешу
      - /var/run # nginx.pid

  backend:
    ports: ["${BACKEND_HOST_PORT:-5000}:${BACKEND_PORT:-5000}"]
    environment:
      - PORT=${BACKEND_PORT:-5000}
    restart: always
    read_only: true
    tmpfs:
      - /tmp # Node.js іноді пише у /tmp


# Launch prod config:
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up
