services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres-data:/var/lib/postgresql/data
    networks: [backend-net]
    restart: unless-stopped

  adminer:
    image: adminer
    ports: ["8081:8080"]
    restart: unless-stopped

  backend:
    image: backend:prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-net
      - frontend-net
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/health"]
      interval: 30s # перевіряти кожні 30с
      timeout: 10s # timeout на відповідь
      retries: 3 # 3 провали → unhealthy
      start_period: 20s # не враховувати перші 20с
    restart: unless-stopped

  frontend:
    image: frontend:prod
    build:
      context: ./frontend
      target: prod
      args:
        VITE_API_URL: ${VITE_API_URL}
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
      db:
        condition: service_healthy
    networks: [frontend-net]
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  frontend-net:
  backend-net:
